### ISSUE TITLE
Complete process of clean exporting of data from Workers.coop CiviCRM

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/workers-coop-map#1]
- [ ] All required data is being exported cleanly
 - [ ] No inappropriate data is being exported
 - [ ] Identifiers are being used when appropriate, in data and field titles
 - [ ] rdf indentifiers are being stored correctly in Civi and exported correctly

**Comment by ColmDC** [comment]
@wu-lee Can we already close this?

**Comment by wu-lee** [comment]
Yes, I think so - I'd need to squint a bit to check off all of those boxes reading the literally, but they are essentially resolved. 
- Yes, all I believe required data is being exported
- No inappropriate data is being exported - we do get non-active co-ops, but currently we filter them out, and later we keep them when we can show the live ones by default and have an option to show non-live cases
- Identifiers are being used in data where they should be - field titles are just what they are and shouldn't change. We have mappings from IDs to human-readable labels in English.
- Just the last component of the RDF indentifiers are being stored, not the whole URL, at our request. This avoids the need to handle `dev.lod.coop` vs `lod.coop` base URI differences, and like versions in the URI. They would typically require the base URI to be stripped off and re-added, complicating life in a way which seems unhelpful.
